apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: panda
  labels:
    app.kubernetes.io/name: panda
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: panda
