apiVersion: v1
kind: Service
metadata:
  name: panda
  labels:
    app.kubernetes.io/name: panda
spec:
  selector:
    app.kubernetes.io/name: panda
  ports:
    - name: http
      port: 8080
      targetPort: http
