name: TinyGo Plugin Validate

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tinygo-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tinygo-version: ["0.33.0", "0.34.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Install TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ matrix.tinygo-version }}

      - name: Install wasm-tools
        run: cargo install wasm-tools

      - name: Validate TinyGo sample plugins
        run: |
          bash ./scripts/validate_tinygo_plugin.sh
          bash ./scripts/validate_tinygo_pci_plugin.sh
